;返回DOS系统
OK MACRO
    MOV AH,4CH
    INT 21H
ENDM
;回车换行
NEXT MACRO
    MOV DX,OFFSET CRLF
    MOV AH,09H
    INT 21H
ENDM
;打印分隔符
GAP MACRO
    MOV DX,OFFSET OUTPUT
    MOV AH,09H
    INT 21H
ENDM
;打印提示输入信息
PS MACRO
    MOV DX,OFFSET INPUT
    MOV AH,09H
    INT 21H
ENDM

EXTRN M1:FAR
EXTRN M2:FAR
EXTRN M3:FAR

DATASEG SEGMENT
    BUFFER  DB 16,?,16 DUP(0)   ;预定义20字节的空间，待输入完成以后，自动获得输出的字符个数
    INPUT   DB "WHAT IS THE DATE(input DD-MM-YYYY)?",'$'
    OUTPUT  DB '-','$'
    CRLF    DB 0AH,0DH,'$'      ;回车换行
DATASEG ENDS
 
STACKSEG SEGMENT
STACKSEG ENDS
 
CODESEG SEGMENT
    ASSUME CS:CODESEG,DS:DATASEG,SS:STACKSEG
START:
    MOV AX,DATASEG
    MOV DS,AX

    PS
    NEXT

    ;字符串输入
    LEA DX,BUFFER
    MOV AH,0AH
    INT 21H

    NEXT

    CALL FAR PTR M1
    GAP
    CALL FAR PTR M2
    GAP
    CALL FAR PTR M3

    OK

CODESEG ENDS
    END START